project:
  type: website
  output-dir: docs/es
  render:
    - "index.qmd"
    - "*-es.qmd"
    - "news-es/*.qmd"
    - "!news"   # Do not render news folder in English
    - "!research" # Do not render research folder in English

website:
  title: "GCO-UVa"
  description: "GCO-UVa: Grupo de Comunicaciones Ópticas de la Universidad de Valladolid (España)."
  navbar:
    # title: false    # Do not display title
    # logo: /images/logogco.jpg   # Display logo
    left:
      - text: Acerca de
        href: about-es.qmd
      - text: Investigación
        href: research-es.qmd
      - text: Miembros
        href: people-es.qmd
      - text: Últimos proyectos
        href: latest-projects-es.qmd
      - text: Resultados
        href: results-es.qmd    
      - text: Premios
        href: awards-es.qmd    
      - text: Noticias
        href: news-es.qmd
    right:
      - text: English
        href: ../en
      - icon: instagram
        href: https://www.instagram.com/gcouva/
      - icon: facebook
        href: https://www.facebook.com/people/Grupo-de-Comunicaciones-%C3%93pticas/
      - icon: linkedin
        href: https://www.linkedin.com/company/grupo-de-comunicaciones-%C3%B3pticas
      - icon: twitter
        href: https://x.com/gco_UVa
      - icon: github
        href: https://github.com/gcouva
  page-navigation: true
  page-footer: 
    left: "[GCO-UVa](http:/gcouva.github.io/gcoweb) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Sitio web desarrollado gracias a la financiación de la Consejería de Educación de la Junta de Castilla y León para la contratación de personal técnico de apoyo a la investigación, cofinanciado por la Unión Europea. Sitio web creado a partir de la plantilla [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) proporcionada por el [Dr. Gang He](http://drganghe.github.io)."
    right:  
      - icon: instagram
        href: https://www.instagram.com/gcouva/
      - icon: facebook
        href: https://www.facebook.com/people/Grupo-de-Comunicaciones-%C3%93pticas/
      - icon: linkedin
        href: https://www.linkedin.com/company/grupo-de-comunicaciones-%C3%B3pticas
      - icon: twitter
        href: https://x.com/gco_UVa
      - icon: github
        href: https://github.com/gcouva
  search:
    location: navbar
    type: textbox
  reader-mode: false
  repo-url: https://github.com/gcouva/gcoweb
  open-graph: true
  twitter-card: true    
  site-url: "https://gcouva.github.io/gcoweb"

format:
  html:
    theme: cosmo
    #theme: materia
    #theme: default
    #theme: litera
    #theme: lumen
    #theme: minty
    #theme: pulse
    #theme: superhero
    ##theme: zephyr
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true 
    link-external-filter: '^https://gcouva.github.io/gcoweb'
