project:
  type: website
  output-dir: docs/en
  render:
    - "*.qmd"
    - "news/*.qmd"
    - "research/*.qmd"
    - "!*-es.qmd"   # Do not render files in Spanish
    - "!news-es"   # Do not render news folder in Spanish
    - "!research-es" # Do not render research folder in Spanish

website:
  title: "GCO-UVa"
  description: "GCO-UVa: Optical Communications Group at Universidad de Valladolid (Spain)."

  navbar:
    # title: false    # Do not display title
    # logo: /images/logogco.jpg   # Display logo
    left:
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: People
        href: people.qmd
      - text: Latest projects
        href: latest-projects.qmd
      - text: Results
        href: results.qmd    
      - text: Awards
        href: awards.qmd    
      - text: News
        href: news.qmd
    right:
      - text: Español
        href: ../es
      - icon: instagram
        href: https://www.instagram.com/gco_uva/
      - icon: facebook
        href: https://www.facebook.com/people/Grupo-de-Comunicaciones-%C3%93pticas/61584502670599/
      - icon: linkedin
        href: https://www.linkedin.com/company/grupo-de-comunicaciones-%C3%B3pticas
      - icon: twitter
        href: https://x.com/gco_UVa
      - icon: github
        href: https://github.com/gcouva
  page-navigation: true
  page-footer: 
    left: "[GCO-UVa](http:/gcouva.github.io/gcoweb) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Website developed thanks to funding by Consejería de Educación de la Junta de Castilla y León for hiring of technical research support staff, cofinanced by the European Union. Website build on [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) provided by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: instagram
        href: https://www.instagram.com/gco_uva/
      - icon: facebook
        href: https://www.facebook.com/people/Grupo-de-Comunicaciones-%C3%93pticas/61584502670599/
      - icon: linkedin
        href: https://www.linkedin.com/company/grupo-de-comunicaciones-%C3%B3pticas
      - icon: twitter
        href: https://x.com/gco_UVa
      - icon: github
        href: https://github.com/gcouva
  search:
    location: navbar
    type: textbox
  reader-mode: false
  repo-url: https://github.com/gcouva/gcoweb
  open-graph: true
  twitter-card: true    
  site-url: "https://gcouva.github.io/gcoweb"

format:
  html:
    theme: cosmo
    #theme: materia
    #theme: default
    #theme: litera
    #theme: lumen
    #theme: minty
    #theme: pulse
    #theme: superhero
    ##theme: zephyr
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true 
    link-external-filter: '^https://gcouva.github.io/gcoweb'
